### ISSUE TITLE
Crash: Totems can not have property facing:up

### ISSUE THREAD

**Issue by lobbienjonsji** [KorDum/TotemDefender_1.7.10#3]
The game crashed whilst unexpected error
Error: java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to up on block totemdefender:diamond_totem, it is not an allowed value

**Comment by KorDum** [comment]
Please full crashlog from pastebin or gist.

**Comment by JoeSGT** [comment]
i was testing this mod and i had crash also here the full logs and it contain the crash report https://paste.ee/p/iZ8ru

**Comment by JoeSGT** [comment]
also a way to reduce this is to get the Wooden Totem and face it in all direction then you'll get the crash

**Comment by KorDum** [comment]
Thanks for answer! Can you say full steps for crash? A can't reproduce...

**Comment by JoeSGT** [comment]
https://gyazo.com/c973692a82f836e402f77d1b4b5a1790 i provide a GIF on how to do it and you can see the facing: cords as well

**Comment by KorDum** [comment]
Thanks! I try to fix it.

**Comment by KorDum** [comment]
Oh yeah, I did it.
Please check [curseforge](https://minecraft.curseforge.com/projects/totem-defender/files) for update 1.2.9.
Thanks a lot!
