### ISSUE TITLE
Totem Tree Wood names

### ISSUE THREAD

**Issue by lebanni** [KorDum/TotemDefender_1.7.10#5]
Can we have different names for the tree wood and the three variants with faces so it would be easier to distinguish them ?

**Comment by KorDum** [comment]
Of course. Can you give me some euphonious variants of naming?

**Comment by KorDum** [comment]
```
tile.log.face_1.name=Totem Indifferent Face
tile.log.face_2.name=Totem Angry Face
tile.log.face_3.name=Totem Scared Face
```
