### ISSUE TITLE
Faced log cut down to generic totem log

### ISSUE THREAD

**Issue by lebanni** [KorDum/TotemDefender_1.7.10#6]
Totem Defender 2.1
https://imgur.com/a/fz250gG

**Comment by KorDum** [comment]
Intresting. Problem only with Waila?

**Comment by lebanni** [comment]
Once cut, the block is actually a Totem Wood (ID #8280/0) in the inventory and not one of the faced ones.

**Comment by KorDum** [comment]
Thanks for report!
Fixed in next version.
