### ISSUE TITLE
Crash at start

### ISSUE THREAD

**Issue by lebanni** [KorDum/TotemDefender_1.7.10#8]
forge-1.12.2-14.23.4.2725-universal.jar
TotemDefender-1.12.2-2.6.jar

[crash-2018-06-30_11.47.46-server.txt](https://github.com/KorDum/TotemDefender/files/2151669/crash-2018-06-30_11.47.46-server.txt)

**Comment by lebanni** [comment]
Same with 2.7.

[crash-2018-06-30_21.48.35-server.txt](https://github.com/KorDum/TotemDefender/files/2152138/crash-2018-06-30_21.48.35-server.txt)

**Comment by KorDum** [comment]
Thanks for report! Crash at server side, right?
Fixed in next version.
